import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from "styled-components";

const FooterStyled = styled.footer`
  text-align: center;
`

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Snake
        </h1>


      </main>

      <FooterStyled>
        by elVengador - {new Date().getFullYear()}
      </FooterStyled>
    </div>
  )
}

export default Home
